name: bulovva
description: Bu Lokasyonda Herşey Var.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.6
  font_awesome_flutter: ^9.1.0
  cool_alert: ^1.1.0
  geolocator: ^7.2.0+1
  url_launcher: ^6.0.7
  shared_preferences: ^2.0.6
  date_format: ^2.0.2
  provider: ^5.0.0
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  intl: ^0.17.0
  firebase_messaging: ^10.0.2
  uuid: ^3.0.4
  flutter_rating_bar: ^4.0.0
  geoflutterfire: ^3.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/night.json
    - assets/standart.json

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400
    - family: Dancing
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400