name: myrest
description: Bu Lokasyonda Herşey Var.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+21

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Localization
  intl: ^0.17.0

  # Firebase
  flutterfire_ui: ^0.3.5+1
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.8
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9

  # Utility
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.2.0
  url_launcher: ^6.0.20
  date_format: ^2.0.5
  geoflutterfire: ^3.0.3
  uuid: ^3.0.6

  # Widgets
  flutter_datetime_picker: ^1.5.1
  cool_alert: ^1.1.0
  flutter_speed_dial: ^5.0.0+1
  curved_navigation_bar: ^1.0.3
  qr_flutter: ^4.0.0
  introduction_screen: ^3.0.0

  # State Management
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # Google
  google_maps_flutter: ^2.1.1

  # Design
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^2.0.5
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
