name: bulovva
description: Bu Lokasyonda Herşey Var.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.11
  font_awesome_flutter: ^9.1.0
  cool_alert: ^1.1.0
  geolocator: ^7.2.0+1
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.8
  date_format: ^2.0.4
  provider: ^6.0.1
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  firebase_messaging: ^10.0.8
  uuid: ^3.0.5
  geoflutterfire: ^3.0.1
  flutter_speed_dial: ^4.4.0+2
  curved_navigation_bar: ^1.0.1
  qr_flutter: ^4.0.0
  pinput: ^1.2.0
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^0.1.3
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/splash_logo.png
    - assets/images/logo.png
    - assets/images/title.png
    - assets/images/app_title.png
    - assets/images/login_logo.png

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400